baseURL = "https://nathenabooks.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Nathena Books"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "books"
name = "Books"
weight = 3
[params]
address = ""
author = "Nathena DelPidio"
copyright = "Copyright &copy; 2020"
description = ""
email = "nathenao@gmail.com"
google_analytics_id = ""
home = "Home"
logo = "images/logo.png"
nav_link_hover_color = "green"
phone = ""
theme_accent_color = "blue"
theme_color = "white"
[params.contact]
enable = false
enable_footer = false
form_action = "#"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[[params.social]]
URL = "https://www.instagram.com/nathenabooks/"
handle = "@nathenabooks"
icon = "ti-instagram"
